### ISSUE TITLE
Add native ffi support in jerryscript.

### ISSUE THREAD

**Issue by lygstate** [jerryscript-project/jerryscript#2283] opened 2018-04-16 13:57 UTC

**Comment by lygstate** [comment] 2018-04-17 13:50
@martijnthe That's very good:), But I am talking about ffi:) for example:
https://github.com/node-ffi-napi/node-ffi-napi
These are different topic:)

**Comment by akosthekiss** [comment] 2018-04-26 22:24
@lygstate The project you've linked is a Node.js addon. JerryScript is not the lightweight equivalent of Node.js. It is "just" an engine. You can rather compare it to the V8 engine that's driving Node.js. Please, consider whether a project that uses JerryScript might be a better fit for your proposal (e.g., IoT.js).

**Comment by lygstate** [comment] 2018-04-27 04:55
use same API for binding create， so we could be able to use a lot of npmjs project

**Comment by akosthekiss** [comment] 2018-04-27 08:27
@lygstate Please note that JerryScript was _never_ intended to (re)use Node.js packages. Samsung/iotjs is a platform on top of JerryScript, that project has goals that you are mentioning.

**Comment by akosthekiss** [comment] 2018-05-10 06:07
Just double checked the referenced project and ffi in general. Although there might be some cases (which I haven't thoroughly elaborated) where libffi, the C library behind node-ffi-napi might be useful, the whole concept of node-ffi-napi is based on dynamic library loading (dlopen), dynamic symbol retrieval (dlsym), etc., which are concepts unknown and alien to the JerryScript engine. So, I'm closing this as out of scope.

Should anyone feel otherwise or even think that it can be implemented, e.g., based on jerry-ext/{arg,module}, then do comment on and/or reopen the issue. (Of course, a working prototype in a PR always helps making a stronger case...)

**Closed by akosthekiss** 2018-05-10 06:07 UTC

**Comment by jan4984** [comment] 2019-04-29 03:22
I know JerryScript will not have native FFI. Just ask here is any project implement the JerryScript FFI?

**Comment by legendecas** [comment] 2019-04-29 03:34
@jan4984 https://github.com/shadow-node/ffi is a simple ffi made for shadow-node with jerryscript API.

**Comment by jan4984** [comment] 2019-05-06 11:25
@legendecas That's good. The problem is I don't need neither want ShadowNode.
