### ISSUE TITLE
mbed debugger error

### ISSUE THREAD

**Issue by RozenAstrayChen** [jerryscript-project/jerryscript#2030] opened 2017-09-29 02:58 UTC
I want to use mbed-cli debugger,so I edit __/mbed-js-example/build/jerryscript/targets/mbedos5__ -> __DEBUG?=1__
my commend is ```gulp --target=NUCLEO_F401RE```
but I got this error
```
Compile [100.0%]: test_env.cpp
Link: mbedos5
/usr/local/Cellar/gcc-arm-none-eabi/20160928/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: ../../../out/NUCLEO_F401RE/mbedos5.elf section `.text' will not fit in region `FLASH'
/usr/local/Cellar/gcc-arm-none-eabi/20160928/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 81380 bytes
collect2: error: ld returned 1 exit status
[ERROR] /usr/local/Cellar/gcc-arm-none-eabi/20160928/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: ../../../out/NUCLEO_F401RE/mbedos5.elf section `.text' will not fit in region `FLASH'
/usr/local/Cellar/gcc-arm-none-eabi/20160928/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 81380 bytes
collect2: error: ld returned 1 exit status

[mbed] ERROR: "/Users/Rozen_mac/anaconda/bin/python" returned error code 1.
[mbed] ERROR: Command "/Users/Rozen_mac/anaconda/bin/python -u /Users/Rozen_mac/code/node/mbed-js-example/build/jerryscript/targets/mbedos5/mbed-os/tools/make.py -t GCC_ARM -m NUCLEO_F401RE --profile ./mbed-os/tools/profiles/debug.json --source . --source ../../ --source ../../../source --build ../../../out/NUCLEO_F401RE -j0 -D CONFIG_MEM_HEAP_AREA_SIZE=(1024*16)" in "/Users/Rozen_mac/code/node/mbed-js-example/build/jerryscript/targets/mbedos5"
---
make[1]: *** [all] Error 1
make: *** [all] Error 2
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Command `make BOARD=NUCLEO_F401RE EXTRAS=` exited with code 2
    at ChildProcess.handleSubShellExit (/Users/Rozen_mac/code/node/mbed-js-example/node_modules/gulp-run/command.js:166:13)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
```

**Comment by akosthekiss** [comment] 2017-10-11 22:12
I cannot comment on the `throw er;` part but the start of the error log seems to be clear about the linked binary not fitting into the flash of your target device ("section .text will not fit in region FLASH" and "region FLASH overflowed by 81380 bytes"). A note though: 81K overflow is a lot. What was the size of the text section with DEBUG=0, and how large is the flash on your device?

**Comment by RozenAstrayChen** [comment] 2017-10-15 18:11
My device is  STM32 NUCLEO F401RE,flash size is ==512KB==

**Comment by akosthekiss** [comment] 2017-10-15 19:29
And what was the size of the program before debug was enabled?

**Comment by RozenAstrayChen** [comment] 2017-10-16 12:21
How I can find the size of program before debug was enabled? I'm not setting this

**Comment by akosthekiss** [comment] 2017-10-16 12:59
I don't see a problem with the linker script (at first glance). As to your question: I use mbed cli for building my project (e.g., `mbed compile --clean`), there I get something like this as the last lines of console output:
```
Total Static RAM memory (data + bss): 16468 bytes
Total Flash memory (text + data): 256063 bytes
```
Do you have anything similar?

**Comment by RozenAstrayChen** [comment] 2017-10-16 13:20
Ya I find this message when i build project 
```
Total Static RAM memory (data + bss): 31152 bytes
Total RAM memory (data + bss + heap + stack): 31152 bytes
Total Flash memory (text + data + misc): 375513 bytes
```

**Comment by akosthekiss** [comment] 2017-10-16 14:08
Okay, I think that you'll have to do without DEBUG=1 for now. I tried a debug build with `mbed compile --clean --profile debug` on my own project and I also got a `region 'FLASH' overflowed by 9248 bytes` error although my starting release size was smaller than yours (and I have the same flash size). I have no idea yet what exactly blows the code to twice the size (but `-O0` for debug vs `-Os` for release  certainly doesn't help).

**Comment by RozenAstrayChen** [comment] 2017-10-16 14:25
Ok Thanks you for your reply. :)

**Comment by akosthekiss** [comment] 2017-10-16 14:38
Closing issue as it's not a bug (neither in mbed-os nor in jerryscript) but simply a debug build not fitting into the flash of a specific device. To be solved by specifying a custom set of compiler flags (e.g., `-Os -g3`) or by defining a custom build profile (https://docs.mbed.com/docs/mbed-os-handbook/en/latest/dev_tools/build_profiles/).

**Closed by akosthekiss** 2017-10-16 14:38 UTC
