### ISSUE TITLE
Assertion 'context_p->token.type != LEXER_RIGHT_PAREN' failed at jerryscript/jerry-core/parser/js/js-parser-statm.c(parser_parse_for_statement_start):1605.

### ISSUE THREAD

**Issue by FlydragonTy** [jerryscript-project/jerryscript#4922] opened 2022-01-04 06:02 UTC
###### JerryScript revision

Commit: [a6ab5e9](https://github.com/jerryscript-project/jerryscript/commit/a6ab5e9abed70cdedf9f4e9c1dc379eb762ebf64)

Version: v3.0.0

###### Build platform

Ubuntu 18.04.5 LTS (Linux 4.19.128-microsoft-standard x86_64)

Ubuntu 18.04.5 LTS (Linux 5.4.0-44-generic x86_64)

###### Build steps

```bash
python ./tools/build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-g --strip=off --lto=off --logging=on --line-info=on --error-message=on --system-allocator=on --stack-limit=20
```

###### Test case
<details>
<summary>poc.js</summary>
<pre><code>

```javascript
function toPrinted(value) {
  return value = value.replace(/\\n/g, 'NL')
    .replace(/\\r/g, 'CR')
    .replace(/[^\x20-\x7E]+/g, escapeString);
}
function escapeString(str) {
  var a, b, c, d;
  var len = str.length;
  var result = "";
  var digits = ["0", "1", "2", "3", "4", "5", "6", "7",
    "8", "9", "A", "B", "C", "D", "E", "F"];
  for (var i = 0; i < len; i++) {
    var ch = str.charCodeAt(i);
    a = digits[ch & 0xf];
    if (ch) {
      c = digits[ch & 0xf];
      ch >>= 4;
      d = digits[ch & 0xf];
      result += "\\u" + d + c + b + a;
    }
  }
}
function reportCompare(expected, actual, description) {

  try {
    gczeal(2, 4);
  } catch (exc1) { }
  var trimMethods = ['trim', 'trimLeft', 'trimRight'];
  var whitespace = [
    {{ : '\u2028', t: 'LINE SEPARATOR' },
  ];
  for (var j = 0; j < trimMethods.length; ++j) {
    var method = trimMethods[j];
    for (var i = 0; i < whitespace.length; ++i) {
      var v = whitespace[i].s;
      var t = whitespace[i].t;
      v = v + v + v;
      str = v;
      expected = '';
      actual = str[method]();
      reportCompare(expected, actual, t + ':' + '"' + toPrinted(str) + '".' + method + '()');
    }
  }
```
</code></pre>
</details>
​	

###### Execution steps & Output

```bash
$ ./jerryscript/build/bin/jerry poc.js

ICE: Assertion 'context_p->token.type != LEXER_RIGHT_PAREN' failed at jerryscript/jerry-core/parser/js/js-parser-statm.c(parser_parse_for_statement_start):1605.
Error: ERR_FAILED_INTERNAL_ASSERTION
[1]    27191 abort      jerry poc.js
```

**Comment by rerobika** [comment] 2022-01-04 10:39
The main issue is similar to #4916. The problem is going to be resolved via #4942.

**Closed by rerobika** 2022-01-04 10:39 UTC
