### ISSUE TITLE
Assertion 'scope_stack_p >= context_p->scope_stack_p' failed at jerry-core/parser/js/js-parser-statm.c(parser_parse_function_statement):741.

### ISSUE THREAD

**Issue by FlydragonTy** [jerryscript-project/jerryscript#4919] opened 2022-01-04 06:00 UTC
###### JerryScript revision

Commit: [a6ab5e9](https://github.com/jerryscript-project/jerryscript/commit/a6ab5e9abed70cdedf9f4e9c1dc379eb762ebf64)

Version: v3.0.0

###### Build platform

Ubuntu 18.04.5 LTS (Linux 4.19.128-microsoft-standard x86_64)

Ubuntu 18.04.5 LTS (Linux 5.4.0-44-generic x86_64)

###### Build steps

```bash
python ./tools/build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-g --strip=off --lto=off --logging=on --line-info=on --error-message=on --system-allocator=on --stack-limit=20
```

###### Test case
<details>
<summary>poc.js</summary>
<pre><code>

```javascript
function JSEtest() {
  const v1 = [
      1337,
      1337
  ];
  let v2 = v1;
  with (100) {
      const v8 = {
          valueOf: 13.37,
          d: -2191938590,
          __proto__: 'ldq5vGcKyJ',
          {: 128
      };
      function v9(v10, v11, v12) {
          v2 = -1000;
          let v15 = arguments;
      }
      for (let v19 = 0; v19 < 100; v19++) {
          const v20 = v9(v8);
      }
  }
}
JSEtest();
```
</code></pre>
</details>
​	

###### Execution steps & Output

```bash
$ ./jerryscript/build/bin/jerry poc.js

ICE: Assertion 'scope_stack_p >= context_p->scope_stack_p' failed at /root/jerryscript/jerry-core/parser/js/js-parser-statm.c(parser_parse_function_statement):741.
Error: ERR_FAILED_INTERNAL_ASSERTION
[1]    23239 abort      jerry poc.js

```

**Comment by rerobika** [comment] 2022-01-04 10:39
The main issue is similar to #4916. The problem is going to be resolved via #4942.

**Closed by rerobika** 2022-01-04 10:39 UTC
